package classes;
// Generated 2016-11-25 10:14:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Restaurant generated by hbm2java
 */
public class Restaurant  implements java.io.Serializable {


     private Integer idresto;
     private Typecuisine typecuisine;
     private String nom;
     private String description;
     private String siteweb;
     private int idMembre;
     private long prixmoyen;
     private String image;
     private Set commentaires = new HashSet(0);

    public Restaurant() {
    }

	
    public Restaurant(Typecuisine typecuisine, String nom, String description, String siteweb, int idMembre, long prixmoyen, String image) {
        this.typecuisine = typecuisine;
        this.nom = nom;
        this.description = description;
        this.siteweb = siteweb;
        this.idMembre = idMembre;
        this.prixmoyen = prixmoyen;
        this.image = image;
    }
    public Restaurant(Typecuisine typecuisine, String nom, String description, String siteweb, int idMembre, long prixmoyen, String image, Set commentaires) {
       this.typecuisine = typecuisine;
       this.nom = nom;
       this.description = description;
       this.siteweb = siteweb;
       this.idMembre = idMembre;
       this.prixmoyen = prixmoyen;
       this.image = image;
       this.commentaires = commentaires;
    }
   
    public Integer getIdresto() {
        return this.idresto;
    }
    
    public void setIdresto(Integer idresto) {
        this.idresto = idresto;
    }
    public Typecuisine getTypecuisine() {
        return this.typecuisine;
    }
    
    public void setTypecuisine(Typecuisine typecuisine) {
        this.typecuisine = typecuisine;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getSiteweb() {
        return this.siteweb;
    }
    
    public void setSiteweb(String siteweb) {
        this.siteweb = siteweb;
    }
    public int getIdMembre() {
        return this.idMembre;
    }
    
    public void setIdMembre(int idMembre) {
        this.idMembre = idMembre;
    }
    public long getPrixmoyen() {
        return this.prixmoyen;
    }
    
    public void setPrixmoyen(long prixmoyen) {
        this.prixmoyen = prixmoyen;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Set getCommentaires() {
        return this.commentaires;
    }
    
    public void setCommentaires(Set commentaires) {
        this.commentaires = commentaires;
    }




}


