package classes;
// Generated 2016-11-25 10:14:50 by Hibernate Tools 4.3.1



/**
 * RestaurantprefereId generated by hbm2java
 */
public class RestaurantprefereId  implements java.io.Serializable {


     private int idmembre;
     private int idrestaurant;

    public RestaurantprefereId() {
    }

    public RestaurantprefereId(int idmembre, int idrestaurant) {
       this.idmembre = idmembre;
       this.idrestaurant = idrestaurant;
    }
   
    public int getIdmembre() {
        return this.idmembre;
    }
    
    public void setIdmembre(int idmembre) {
        this.idmembre = idmembre;
    }
    public int getIdrestaurant() {
        return this.idrestaurant;
    }
    
    public void setIdrestaurant(int idrestaurant) {
        this.idrestaurant = idrestaurant;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RestaurantprefereId) ) return false;
		 RestaurantprefereId castOther = ( RestaurantprefereId ) other; 
         
		 return (this.getIdmembre()==castOther.getIdmembre())
 && (this.getIdrestaurant()==castOther.getIdrestaurant());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdmembre();
         result = 37 * result + this.getIdrestaurant();
         return result;
   }   


}


