package classes;
// Generated 2016-11-25 10:14:50 by Hibernate Tools 4.3.1



/**
 * Restaurantprefere generated by hbm2java
 */
public class Restaurantprefere  implements java.io.Serializable {


     private RestaurantprefereId id;

    public Restaurantprefere() {
    }

    public Restaurantprefere(RestaurantprefereId id) {
       this.id = id;
    }
   
    public RestaurantprefereId getId() {
        return this.id;
    }
    
    public void setId(RestaurantprefereId id) {
        this.id = id;
    }




}


