package classes;
// Generated 2016-11-25 10:14:50 by Hibernate Tools 4.3.1



/**
 * TypecuisinefavorisId generated by hbm2java
 */
public class TypecuisinefavorisId  implements java.io.Serializable {


     private int idmembre;
     private int idcuisine;

    public TypecuisinefavorisId() {
    }

    public TypecuisinefavorisId(int idmembre, int idcuisine) {
       this.idmembre = idmembre;
       this.idcuisine = idcuisine;
    }
   
    public int getIdmembre() {
        return this.idmembre;
    }
    
    public void setIdmembre(int idmembre) {
        this.idmembre = idmembre;
    }
    public int getIdcuisine() {
        return this.idcuisine;
    }
    
    public void setIdcuisine(int idcuisine) {
        this.idcuisine = idcuisine;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TypecuisinefavorisId) ) return false;
		 TypecuisinefavorisId castOther = ( TypecuisinefavorisId ) other; 
         
		 return (this.getIdmembre()==castOther.getIdmembre())
 && (this.getIdcuisine()==castOther.getIdcuisine());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdmembre();
         result = 37 * result + this.getIdcuisine();
         return result;
   }   


}


