package classes;
// Generated 2016-11-25 10:14:50 by Hibernate Tools 4.3.1



/**
 * Typecuisinefavoris generated by hbm2java
 */
public class Typecuisinefavoris  implements java.io.Serializable {


     private TypecuisinefavorisId id;

    public Typecuisinefavoris() {
    }

    public Typecuisinefavoris(TypecuisinefavorisId id) {
       this.id = id;
    }
   
    public TypecuisinefavorisId getId() {
        return this.id;
    }
    
    public void setId(TypecuisinefavorisId id) {
        this.id = id;
    }




}


